window.SITE = {
  brand: {
    name: "Teddz",
    altNames: "Teddz · Teddzfr · Frteddz",
    role: "Web Developer & One-Person Studio",
    baseUrl: "https://frteddz.github.io",
    siteName: "Teddz — Portfolio",
  },
  links: {
    github: "https://github.com/frteddz",
    x: "https://x.com/teddzfr",
    youtube: "https://www.youtube.com/@frteddz",
    instagram: "https://www.instagram.com/teddzfr/",
    tiktok: "https://www.tiktok.com/@teddz.fr",
    email: "mailto:teddzfr@proton.me",
    emailPlain: "teddzfr@proton.me",
  },
  categories: [
    { id: "web", tone: "dark" },
    { id: "asset", tone: "light" },
    { id: "dev", tone: "dark" },
    { id: "content", tone: "light" },
  ],
  projects: {
    web: [
      {
        slug: "crashout",
        name: "CrashOUT",
        url: "https://dont-crashout.vercel.app/",
        img: { webp: "crashout.webp", jpg: "crashout.jpg" },
        desc: {
          en: "The description is basically in the name.",
          ar: "الوصف واضح من الاسم.",
        },
        tag: { en: "GameWeb", ar: "لعبة ويب" },
        alt: {
          en: "CrashOUT — a web game site, screenshot",
          ar: "CrashOUT — موقع ألعاب ويب، لقطة شاشة",
        },
      },
      {
        slug: "aethercoremc",
        name: "AetherCoreMc",
        url: "https://aethercoremc.vercel.app/",
        img: { webp: "aethercoremc.webp", jpg: "aethercoremc.jpg" },
        desc: {
          en: "A Minecraft utility hub with 15+ utilities.",
          ar: "مركز أدوات لماينكرافت يضم أكثر من 15 أداة.",
        },
        tag: { en: "Minecraft Utilities", ar: "أدوات ماينكرافت" },
        alt: {
          en: "AetherCoreMc — Minecraft utility hub, screenshot",
          ar: "AetherCoreMc — مركز أدوات ماينكرافت، لقطة شاشة",
        },
      },
      {
        slug: "a-random-website",
        name: "A Random Website",
        url: "https://a-random-website.vercel.app/",
        img: { webp: "a-random-website.webp", jpg: "a-random-website.jpg" },
        desc: {
          en: "A website with 99+ random addictive mini games.",
          ar: "موقع يضم أكثر من 99 لعبة مصغّرة عشوائية ومدمنة.",
        },
        tag: { en: "Mini Games", ar: "ألعاب مصغّرة" },
        alt: {
          en: "A Random Website — 99+ mini games, screenshot",
          ar: "A Random Website — أكثر من 99 لعبة مصغّرة، لقطة شاشة",
        },
      },
      {
        slug: "euthenia-studio",
        name: "Euthenia Studio",
        url: "https://frteddz.github.io/Euthenia-Studio-Website/#",
        img: { webp: "euthenia-studio.webp", jpg: "euthenia-studio.jpg" },
        desc: {
          en: "My personal software studio — simple, fast, privacy-first tools built by one dev.",
          ar: "استوديو البرمجيات الشخصي الخاص بي — أدوات بسيطة وسريعة وخصوصية أولًا، من صنع مطوّر واحد.",
        },
        tag: { en: "One-Person Studio", ar: "استوديو فردي" },
        alt: {
          en: "Euthenia Studio — personal software studio, screenshot",
          ar: "استوديو Euthenia — استوديو برمجيات شخصي، لقطة شاشة",
        },
      },
      {
        slug: "mghac",
        name: "Mabuhay Golden Harvest Agriculture Cooperative",
        url: "https://mghac.vercel.app/index.html",
        img: { webp: "mghac.webp", jpg: "mghac.jpg" },
        desc: {
          en: "A community-based agriculture cooperative cultivating sustainable communities, empowering farmers, and inspiring the next generation.",
          ar: "تعاونية زراعية مجتمعية تزرع مجتمعات مستدامة، وتمكّن المزارعين، وتُلهم الجيل القادم.",
        },
        tag: { en: "Cooperative", ar: "تعاونية" },
        alt: {
          en: "Mabuhay Golden Harvest Agriculture Cooperative, screenshot",
          ar: "تعاونية الحصاد الذهبي الزراعية، لقطة شاشة",
        },
      },
      {
        slug: "massage-site",
        name: "Body Massage",
        url: "https://massage-site-rho.vercel.app/",
        img: { webp: "massage-site.webp", jpg: "massage-site.jpg" },
        desc: {
          en: "Home service massage.",
          ar: "تدليك بخدمة منزلية.",
        },
        tag: { en: "Web App", ar: "تطبيق ويب" },
        alt: {
          en: "Body Massage — home service massage, screenshot",
          ar: "تدليك الجسم — خدمة تدليك منزلية، لقطة شاشة",
        },
      },
      {
        slug: "shalhome",
        name: "ShalHome",
        url: "https://shalhome.vercel.app/",
        img: { webp: "shalhome.webp", jpg: "shalhome.jpg" },
        desc: {
          en: "A home of peace.",
          ar: "منزل من السلام.",
        },
        tag: { en: "Web App", ar: "تطبيق ويب" },
        alt: {
          en: "ShalHome — a home of peace, screenshot",
          ar: "ShalHome — منزل من السلام، لقطة شاشة",
        },
      },
      {
        slug: "staycation",
        name: "A-J Staycation",
        url: "https://staycation-airbnb.vercel.app/",
        img: { webp: "staycation.webp", jpg: "staycation.jpg" },
        desc: {
          en: "S Residence Tower 1 · Pasay City.",
          ar: "برج S Residence 1 · مدينة باساي.",
        },
        tag: { en: "Staycation", ar: "عطلة" },
        alt: {
          en: "A-J Staycation — S Residence Tower 1 · Pasay City, screenshot",
          ar: "A-J Staycation — برج S Residence 1 · مدينة باساي، لقطة شاشة",
        },
      },
      {
        slug: "juno",
        name: "JUNO",
        url: "https://frteddz.github.io/JUNO/",
        img: { webp: "juno.webp", jpg: "juno.jpg" },
        desc: {
          en: "A local-first terminal assistant. Open apps, set timers, do the math. Optional DeepSeek AI.",
          ar: "مساعد محلي في الطرفية. افتح التطبيقات، وعيّن مؤقتين، واحسب. DeepSeek AI اختياري.",
        },
        tag: { en: "Terminal Assistant", ar: "مساعد طرفية" },
        alt: {
          en: "JUNO — terminal assistant, screenshot",
          ar: "JUNO — مساعد طرفية، لقطة شاشة",
        },
      },
      {
        slug: "cedrus",
        name: "Cedrus CLI",
        url: "https://frteddz.github.io/cedrus/",
        img: { webp: "cedrus.webp", jpg: "cedrus.jpg" },
        desc: {
          en: "A command-line tool that connects to any web-based public AI and turns it into an IDE.",
          ar: "أداة سطر أوامر تتصل بأي ذكاء اصطناعي عام ويحوّله إلى بيئة تطوير متكاملة.",
        },
        tag: { en: "CLI Tool", ar: "أداة سطر أوامر" },
        alt: {
          en: "Cedrus CLI — turn any web AI into a coding agent, screenshot",
          ar: "Cedrus CLI — حوّل أي ذكاء اصطناعي إلى عميل برمجة، لقطة شاشة",
        },
      },
      {
        slug: "cedrus-site",
        name: "Cedrus Site",
        url: "https://frteddz.github.io/cedrus-site/",
        img: { webp: "cedrus-site.webp", jpg: "cedrus-site.jpg" },
        desc: {
          en: "Cedrus — an AI assistant that runs as a terminal app. Read, write, search and talk to your project.",
          ar: "Cedrus — مساعد ذكاء اصطناعي يعمل كتطبيق طرفية. اقرأ واطبع وابحث وتحدث مع مشروعك.",
        },
        tag: { en: "Showcase", ar: "عرض" },
        alt: {
          en: "Cedrus — AI in the terminal, screenshot",
          ar: "Cedrus — ذكاء اصطناعي في الطرفية، لقطة شاشة",
        },
      },
      {
        slug: "kilter",
        name: "Kilter",
        url: "https://frteddz.github.io/Kilter-web/",
        img: { webp: "kilter.webp", jpg: "kilter.jpg" },
        desc: {
          en: "A falling block puzzle game by Euthenia Studio.",
          ar: "لعبة ألغازسقط كتل من إنتاج Euthenia Studio.",
        },
        tag: { en: "Puzzle Game", ar: "لعبة ألغاز" },
        alt: {
          en: "Kilter — falling block puzzle game, screenshot",
          ar: "Kilter — لعبة ألغاز سقط كتل، لقطة شاشة",
        },
      },
      {
        slug: "spindeck",
        name: "SpinDeck",
        url: "https://frteddz.github.io/SpinDeck-web/",
        img: { webp: "spindeck.webp", jpg: "spindeck.jpg" },
        desc: {
          en: "A spinner and roulette tool by Euthenia Studio.",
          ar: "أداة دوران ودولاب حظ من إنتاج Euthenia Studio.",
        },
        tag: { en: "Spinner", ar: "أداة دوران" },
        alt: {
          en: "SpinDeck — spinner and roulette tool, screenshot",
          ar: "SpinDeck — أداة دوران ودولاب حظ، لقطة شاشة",
        },
      },
      {
        slug: "tonetrail",
        name: "ToneTrail",
        url: "https://frteddz.github.io/ToneTrail-web/",
        img: { webp: "tonetrail.webp", jpg: "tonetrail.jpg" },
        desc: {
          en: "A tone and sound exploration tool by Euthenia Studio.",
          ar: "أداة استكشاف النغمات والأصوات من إنتاج Euthenia Studio.",
        },
        tag: { en: "Sound Tool", ar: "أداة صوت" },
        alt: {
          en: "ToneTrail — tone and sound exploration tool, screenshot",
          ar: "ToneTrail — أداة استكشاف النغمات والأصوات، لقطة شاشة",
        },
      },
      {
        slug: "starmap",
        name: "StarMap",
        url: "https://frteddz.github.io/StarMap-web/",
        img: { webp: "starmap.webp", jpg: "starmap.jpg" },
        desc: {
          en: "Night sky poster generator by Euthenia Studio.",
          ar: "مُولّد ملصقات سماء ليلية من إنتاج Euthenia Studio.",
        },
        tag: { en: "Poster Generator", ar: "مُولّد ملصقات" },
        alt: {
          en: "StarMap — night sky poster generator, screenshot",
          ar: "StarMap — مُولّد ملصقات سماء ليلية، لقطة شاشة",
        },
      },
      {
        slug: "popcluster",
        name: "PopCluster",
        url: "https://frteddz.github.io/PopCluster-web/",
        img: { webp: "popcluster.webp", jpg: "popcluster.jpg" },
        desc: {
          en: "A bubble cluster popping game by Euthenia Studio.",
          ar: "لعبة فقاعات من إنتاج Euthenia Studio.",
        },
        tag: { en: "Bubble Game", ar: "لعبة فقاعات" },
        alt: {
          en: "PopCluster — bubble cluster popping game, screenshot",
          ar: "PopCluster — لعبة فقاعات، لقطة شاشة",
        },
      },
      {
        slug: "soundlayers",
        name: "SoundLayers",
        url: "https://frteddz.github.io/SoundLayers-web/",
        img: { webp: "soundlayers.webp", jpg: "soundlayers.jpg" },
        desc: {
          en: "An audio layering tool by Euthenia Studio.",
          ar: "أداة طبقة صوتية من إنتاج Euthenia Studio.",
        },
        tag: { en: "Audio Tool", ar: "أداة صوتية" },
        alt: {
          en: "SoundLayers — audio layering tool, screenshot",
          ar: "SoundLayers — أداة طبقة صوتية، لقطة شاشة",
        },
      },
      {
        slug: "cluegrid",
        name: "ClueGrid",
        url: "https://frteddz.github.io/ClueGrid-web/",
        img: { webp: "cluegrid.webp", jpg: "cluegrid.jpg" },
        desc: {
          en: "A word puzzle game by Euthenia Studio.",
          ar: "لعبة ألغاز كلمات من إنتاج Euthenia Studio.",
        },
        tag: { en: "Word Puzzle", ar: "لغز كلمات" },
        alt: {
          en: "ClueGrid — word puzzle game, screenshot",
          ar: "ClueGrid — لعبة ألغاز كلمات، لقطة شاشة",
        },
      },
      {
        slug: "flowstate",
        name: "FlowState",
        url: "https://frteddz.github.io/FlowState-web/",
        img: { webp: "flowstate.webp", jpg: "flowstate.jpg" },
        desc: {
          en: "A flow state game by Euthenia Studio.",
          ar: "لعبة حالة التدفق من إنتاج Euthenia Studio.",
        },
        tag: { en: "Flow Game", ar: "لعبة تدفق" },
        alt: {
          en: "FlowState — flow state game, screenshot",
          ar: "FlowState — لعبة حالة التدفق، لقطة شاشة",
        },
      },
      {
        slug: "triviavoyager",
        name: "TriviaVoyager",
        url: "https://frteddz.github.io/TriviaVoyager-web/",
        img: { webp: "triviavoyager.webp", jpg: "triviavoyager.jpg" },
        desc: {
          en: "A trivia quiz game by Euthenia Studio.",
          ar: "لعبة أسئلة معلومات عامة من إنتاج Euthenia Studio.",
        },
        tag: { en: "Trivia Quiz", ar: "أسئلة معلومات" },
        alt: {
          en: "TriviaVoyager — trivia quiz game, screenshot",
          ar: "TriviaVoyager — لعبة أسئلة معلومات عامة، لقطة شاشة",
        },
      },
      {
        slug: "lastsignal",
        name: "LastSignal",
        url: "https://frteddz.github.io/LastSignal-web/",
        img: { webp: "lastsignal.webp", jpg: "lastsignal.jpg" },
        desc: {
          en: "A space-themed game by Euthenia Studio.",
          ar: "لعبة فضائية من إنتاج Euthenia Studio.",
        },
        tag: { en: "Space Game", ar: "لعبة فضائية" },
        alt: {
          en: "LastSignal — space-themed game, screenshot",
          ar: "LastSignal — لعبة فضائية، لقطة شاشة",
        },
      },
      {
        slug: "pixelstudio",
        name: "PixelStudio",
        url: "https://frteddz.github.io/PixelStudio-web/",
        img: { webp: "pixelstudio.webp", jpg: "pixelstudio.jpg" },
        desc: {
          en: "A browser-based pixel art editor with pen, fill, erase, and export.",
          ar: "محرر فن بيكسل في المتصفح مع قلم وملء ومسح وتصدير.",
        },
        tag: { en: "Pixel Art", ar: "فن بيكسل" },
        alt: {
          en: "PixelStudio — browser-based pixel art editor, screenshot",
          ar: "PixelStudio — محرر فن بيكسل في المتصفح، لقطة شاشة",
        },
      },
      {
        slug: "pixelshrink",
        name: "PixelShrink",
        url: "https://frteddz.github.io/PixelShrink-web/",
        img: { webp: "pixelshrink.webp", jpg: "pixelshrink.jpg" },
        desc: {
          en: "Free batch image compression tool. Compress PNG, JPG, WebP images without losing quality. No uploads, no servers, 100% private.",
          ar: "أداة ضغط صور مجانية بالجملة. اضغط صور PNG وJPG وWebP دون فقدان الجودة. بدون رفع، بدون خوادم، خصوصية 100%.",
        },
        tag: { en: "Image Tool", ar: "أداة صور" },
        alt: {
          en: "PixelShrink — free batch image compression tool, screenshot",
          ar: "PixelShrink — أداة ضغط صور مجانية بالجملة، لقطة شاشة",
        },
      },
      {
        slug: "studyflow",
        name: "StudyFlow",
        url: "https://frteddz.github.io/StudyFlow-web/",
        img: { webp: "studyflow.webp", jpg: "studyflow.jpg" },
        desc: {
          en: "Free modern study planner. Organize subjects, track tasks, manage study sessions with a Pomodoro timer, and plan your calendar.",
          ar: "مُنظّم دراسة حديث مجاني. نظّم المواد، وتتبّع المهام، وأدر جلسات الدراسة مؤقت بومودورو، وخطط تقويمك.",
        },
        tag: { en: "Study Planner", ar: "مُنظّم دراسة" },
        alt: {
          en: "StudyFlow — free modern study planner, screenshot",
          ar: "StudyFlow — مُنظّم دراسة حديث مجاني، لقطة شاشة",
        },
      },
      {
        slug: "qrflow",
        name: "QRFlow",
        url: "https://frteddz.github.io/QRFlow-web/",
        img: { webp: "qrflow.webp", jpg: "qrflow.jpg" },
        desc: {
          en: "Free QR code generator and scanner. Create custom QR codes with colors and logos, or scan QR codes instantly.",
          ar: "مُولّد ومسح أكواد QR مجاني. أنشئ أكواد QR مخصصة بألوان وشعارات، أو امسح أكواد QR فورًا.",
        },
        tag: { en: "QR Codes", ar: "أكواد QR" },
        alt: {
          en: "QRFlow — free QR code generator and scanner, screenshot",
          ar: "QRFlow — مُولّد ومسح أكواد QR مجاني، لقطة شاشة",
        },
      },
      {
        slug: "quickrename",
        name: "QuickRename",
        url: "https://frteddz.github.io/QuickRename-web/",
        img: { webp: "quickrename.webp", jpg: "quickrename.jpg" },
        desc: {
          en: "Free bulk file renaming utility. Rename multiple files at once with powerful rules and patterns.",
          ar: "أداة إعادة تسمية ملفات بالجملة مجانية. أعد تسمية ملفات متعددة دفعة واحدة بقواعد وأنماط قوية.",
        },
        tag: { en: "File Tool", ar: "أداة ملفات" },
        alt: {
          en: "QuickRename — free bulk file renaming utility, screenshot",
          ar: "QuickRename — أداة إعادة تسمية ملفات بالجملة مجانية، لقطة شاشة",
        },
      },
      {
        slug: "pngforge",
        name: "PngForge",
        url: "https://frteddz.github.io/PngForge-web/",
        img: { webp: "pngforge.webp", jpg: "pngforge.jpg" },
        desc: {
          en: "Free online image converter. Convert PNG, JPG, WebP, and AVIF formats instantly in your browser.",
          ar: "محوّل صور مجاني عبر الإنترنت. حوّل صيغ PNG وJPG وWebP وAVIF فورًا في متصفحك.",
        },
        tag: { en: "Image Converter", ar: "محوّل صور" },
        alt: {
          en: "PngForge — free online image converter, screenshot",
          ar: "PngForge — محوّل صور مجاني عبر الإنترنت، لقطة شاشة",
        },
      },
      {
        slug: "folderscope",
        name: "FolderScope",
        url: "https://frteddz.github.io/FolderScope-web/",
        img: { webp: "folderscope.webp", jpg: "folderscope.jpg" },
        desc: {
          en: "Free disk usage visualizer. Scan folders and visualize storage space usage with interactive charts.",
          ar: "مُظهر استخدام القرص المجاني. امسح المجلدات وتصوّر استخدام مساحة التخزين برسوم بيانية تفاعلية.",
        },
        tag: { en: "Disk Tool", ar: "أداة قرص" },
        alt: {
          en: "FolderScope — free disk usage visualizer, screenshot",
          ar: "FolderScope — مُظهر استخدام القرص المجاني، لقطة شاشة",
        },
      },
      {
        slug: "pdfmerge",
        name: "PDFMerge",
        url: "https://frteddz.github.io/PDFMerge-web/",
        img: { webp: "pdfmerge.webp", jpg: "pdfmerge.jpg" },
        desc: {
          en: "Free online PDF toolkit. Merge, split, rotate, and rearrange PDF pages in your browser.",
          ar: "مجموعة أدوات PDF مجانية عبر الإنترنت. ادمج وافصل ولفّ وأعد ترتيب صفحات PDF في متصفحك.",
        },
        tag: { en: "PDF Tool", ar: "أداة PDF" },
        alt: {
          en: "PDFMerge — free online PDF toolkit, screenshot",
          ar: "PDFMerge — مجموعة أدوات PDF مجانية عبر الإنترنت، لقطة شاشة",
        },
      },
      {
        slug: "colorsnap",
        name: "ColorSnap",
        url: "https://frteddz.github.io/ColorSnap-web/",
        img: { webp: "colorsnap.webp", jpg: "colorsnap.jpg" },
        desc: {
          en: "Free professional color picker. Pick, save, and organize colors with hex, RGB, HSL values. Create and export color palettes.",
          ar: "منتقي ألوان احترافي مجاني. اختر واحفظ ونظّم الألوان بقيم hex وRGB وHSL. أنشئ وصدّر لوحات ألوان.",
        },
        tag: { en: "Color Picker", ar: "منتقي ألوان" },
        alt: {
          en: "ColorSnap — free professional color picker, screenshot",
          ar: "ColorSnap — منتقي ألوان احترافي مجاني، لقطة شاشة",
        },
      },
      {
        slug: "backupbuddy",
        name: "BackupBuddy",
        url: "https://frteddz.github.io/BackupBuddy-web/",
        img: { webp: "backupbuddy.webp", jpg: "backupbuddy.jpg" },
        desc: {
          en: "Free browser-based backup utility. Manage, schedule, and restore your browser data backups.",
          ar: "أداة نسخ احتياطي مجانية في المتصفح. أدِر وجدول واستعد نسخ احتياطية لبيانات المتصفح.",
        },
        tag: { en: "Backup Tool", ar: "أداة نسخ احتياطي" },
        alt: {
          en: "BackupBuddy — free browser-based backup utility, screenshot",
          ar: "BackupBuddy — أداة نسخ احتياطي مجانية في المتصفح، لقطة شاشة",
        },
      },
      {
        slug: "clipvault",
        name: "ClipVault",
        url: "https://frteddz.github.io/ClipVault-web/",
        img: { webp: "clipvault.webp", jpg: "clipvault.jpg" },
        desc: {
          en: "Free clipboard history manager for your browser. Save, search, organize, and pin clipboard items with categories.",
          ar: "مدير سجل الحافظة المجاني لمتصفحك. احفظ وابحث ونظّم وثبّت عناصر الحافظة بالفئات.",
        },
        tag: { en: "Clipboard Manager", ar: "مدير حافظة" },
        alt: {
          en: "ClipVault — free clipboard history manager, screenshot",
          ar: "ClipVault — مدير سجل حافظة مجاني، لقطة شاشة",
        },
      },
    ],
    asset: [
      {
        slug: "modrinth",
        name: "Modrinth Creator",
        url: "https://modrinth.com/user/teddz",
        img: { webp: "modrinth.webp", jpg: "modrinth.jpg" },
        desc: {
          en: "Developing highly optimized PvP resource packs and UI layouts focused on competitive visibility and frame-rate optimization.",
          ar: "تطوير حزم موارد PvP محسّنة بعناية وتخطيطات واجهات تركّز على الرؤية التنافسية وتحسين معدل الإطارات.",
        },
        tag: { en: "Texturing · Optimization", ar: "تلوين · تحسين" },
        alt: {
          en: "Modrinth creator profile, screenshot",
          ar: "ملف Modrinth، لقطة شاشة",
        },
      },
    ],
    dev: [
      {
        slug: "builtbybit",
        name: "BuiltByBit",
        url: "https://builtbybit.com/members/teddz.672080/",
        img: { webp: "builtbybit.webp", jpg: "builtbybit.jpg" },
        desc: {
          en: "Providing premium configuration services, custom setups, and administrative assets for community server networks.",
          ar: "تقديم خدمات إعدادات متميزة وتجهيزات مخصصة وأصول إدارية لشبكات سيرفرات المجتمعات.",
        },
        tag: { en: "Configurations", ar: "إعدادات" },
        alt: {
          en: "BuiltByBit profile, screenshot",
          ar: "ملف BuiltByBit، لقطة شاشة",
        },
      },
      {
        slug: "fiverr",
        name: "Fiverr",
        url: null,
        img: null,
        desc: {
          en: "Freelance development shop offering premium configuration services and custom setups.",
          ar: "متجر تطوير مستقل يقدم خدمات إعدادات متميزة وتجهيزات مخصصة.",
        },
        tag: { en: "Freelance", ar: "عمل حر" },
        alt: { en: "Fiverr shop — abstract placeholder", ar: "متجر Fiverr — صورة تجريدية" },
      },
    ],
    content: [
      {
        slug: "youtube",
        name: "YouTube",
        url: "https://www.youtube.com/@frteddz",
        img: null,
        desc: {
          en: "Producing fast-paced video content, clip pacing templates, and gaming media.",
          ar: "إنتاج محتوى فيديو سريع الإيقاع، قوالب توزيع للمقاطع، ووسائط ألعاب.",
        },
        tag: { en: "Video Editing", ar: "مونتاج فيديو" },
        alt: { en: "YouTube channel — abstract placeholder", ar: "قناة يوتيوب — صورة تجريدية" },
      },
      {
        slug: "tiktok",
        name: "TikTok",
        url: "https://www.tiktok.com/@teddz.fr",
        img: null,
        desc: {
          en: "Gaming media and short-form content across platforms.",
          ar: "وسائط ألعاب ومحتوى قصير عبر المنصات.",
        },
        tag: { en: "Short-form", ar: "محتوى قصير" },
        alt: { en: "TikTok profile — abstract placeholder", ar: "ملف TikTok — صورة تجريدية" },
      },
    ],
  },
  t: {
    en: {
      "nav.work": "Work",
      "nav.about": "About",
      "nav.services": "Services",
      "nav.contact": "Contact",
      "nav.menu": "Open menu",
      "nav.close": "Close menu",
      "nav.lang.ar": "العربية",
      "nav.lang.en": "English",
      "a11y.skip": "Skip to content",
      "hero.eyebrow": "Web Developer · One-Person Studio",
      "hero.altnames": "Teddz · Teddzfr · Frteddz",
      "hero.tagline.pre": "Simple, fast,",
      "hero.tagline.accent": "privacy-first.",
      "hero.lead": "Web developer and one-person studio building websites, tools, and games that are simple, fast, and respect your privacy.",
      "hero.cta.work": "View work",
      "hero.cta.contact": "Get in touch",
      "hero.scroll": "Scroll to explore",
      "m1": "Web Development",
      "m2": "UI Layouts",
      "m3": "Minecraft Resource Packs",
      "m4": "Privacy First",
      "m5": "Performance",
      "m6": "Video Editing",
      "m8": "Clean Code",
      "about.eyebrow": "About",
      "about.title": "Software that respects the person using it.",
      "about.body1": "Euthenia Studio is my personal software studio — a place to publish the tools and projects I build. Everything here is made by me, Teddz, one developer at a time.",
      "about.body2": "I believe software should be simple, fast, and respect your privacy.",
      "v1.t": "Built by One Dev",
      "v1.d": "Every project is crafted by Teddz — one developer, from idea to launch.",
      "v2.t": "Privacy First",
      "v2.d": "Tools that run in your browser. No tracking, no data leaving your device.",
      "v3.t": "Always Free at Core",
      "v3.d": "The essential features of every tool stay free. No paywalls, no tricks.",
      "v4.t": "Open to Contributors",
      "v4.d": "Want to publish a project here? My inbox is open — let's build together.",
      "services.eyebrow": "What I do",
      "services.title": "Four lanes, one developer.",
      "s1.t": "Web Development",
      "s1.d": "Fast, accessible websites and web apps — simple by design.",
      "s2.t": "Asset & Resource Design",
      "s2.d": "Highly optimized PvP resource packs and UI layouts for competitive visibility and frame-rate.",
      "s3.t": "Dev & Freelance Services",
      "s3.d": "Premium configurations, custom setups, and admin assets for server networks.",
      "s4.t": "Content & Media",
      "s4.d": "Fast-paced gaming content, clip pacing, and video editing across platforms.",
      "catalog.eyebrow": "Selected Work",
      "catalog.title": "Projects",
      "catalog.lead": "Four lanes of work. Jump between them, or scroll through.",
      "catalog.hint": "Scroll · or jump:",
      "cat.web": "Web Projects",
      "cat.asset": "Asset Design",
      "cat.dev": "Dev Services",
      "cat.content": "Content & Media",
      "cat.count": "projects",
      "link.open": "Open",
      "contact.eyebrow": "Contact",
      "contact.title": "Let's build something together.",
      "contact.sub": "Have a project, a server to set up, or just want to say hi? My inbox is open.",
      "contact.cta": "Email me",
      "footer.top": "Back to top",
      "footer.line": "© {year} Teddz — built by one developer.",
      "meta.title": "Teddz — Web Developer & One-Person Studio",
      "meta.desc": "Simple, fast, privacy-first. Web developer and one-person studio building websites, tools, and games.",
    },
    ar: {
      "nav.work": "الأعمال",
      "nav.about": "من أنا",
      "nav.services": "الخدمات",
      "nav.contact": "تواصل",
      "nav.menu": "افتح القائمة",
      "nav.close": "أغلق القائمة",
      "nav.lang.ar": "العربية",
      "nav.lang.en": "English",
      "a11y.skip": "تخطّي إلى المحتوى",
      "hero.eyebrow": "مطوّر ويب · استوديو فردي",
      "hero.altnames": "تيدز · Teddzfr · Frteddz",
      "hero.tagline.pre": "بسيطة، سريعة،",
      "hero.tagline.accent": "خصوصيتك أولًا.",
      "hero.lead": "مطوّر ويب يدير استوديو فرديًا — أبني مواقع وأدوات وألعابًا بسيطة وسريعة وتحترم خصوصيتك.",
      "hero.cta.work": "شاهد أعمالي",
      "hero.cta.contact": "تواصل معي",
      "hero.scroll": "مرّر للاستكشاف",
      "m1": "تطوير الويب",
      "m2": "تصاميم واجهات",
      "m3": "حزم موارد ماينكرافت",
      "m4": "الخصوصية أولًا",
      "m5": "الأداء",
      "m6": "مونتاج الفيديو",
      "m8": "كود نظيف",
      "about.eyebrow": "من أنا",
      "about.title": "برمجيات تحترم من يستخدمها.",
      "about.body1": "استوديو Euthenia هو استوديو البرمجيات الشخصي الخاص بي — مكان أنشر فيه الأدوات والمشاريع التي أبنيها. كل شيء هنا صنعه أنا، Teddz، مطوّرًا واحدًا في كل مرة.",
      "about.body2": "أؤمن أن البرمجيات يجب أن تكون بسيطة وسريعة وتحترم خصوصيتك.",
      "v1.t": "من صنع مطوّر واحد",
      "v1.d": "كل مشروع يصنعه Teddz — مطوّر واحد، من الفكرة حتى الإطلاق.",
      "v2.t": "الخصوصية أولًا",
      "v2.d": "أدوات تعمل في متصفحك. لا تتبّع، ولا بيانات تغادر جهازك.",
      "v3.t": "مجاني في جوهره",
      "v3.d": "الميزات الأساسية لكل أداة تبقى مجانية دائمًا. لا جدران دفع ولا حيل.",
      "v4.t": "مفتوح للمساهمين",
      "v4.d": "تريد نشر مشروع هنا؟ بريدي مفتوح — لنبنِ معًا.",
      "services.eyebrow": "ماذا أفعل",
      "services.title": "أربعة مسارات، مطوّر واحد.",
      "s1.t": "تطوير الويب",
      "s1.d": "مواقع وتطبيقات ويب سريعة وسهلة الوصول — بسيطة بالتصميم.",
      "s2.t": "تصميم الأصول والموارد",
      "s2.d": "حزم موارد PvP محسّنة بعناية وتخطيطات واجهات للرؤية التنافسية وتحسين معدل الإطارات.",
      "s3.t": "التطوير والعمل الحر",
      "s3.d": "إعدادات متميزة وتجهيزات مخصصة وأصول إدارية لشبكات السيرفرات.",
      "s4.t": "المحتوى والإعلام",
      "s4.d": "محتوى ألعاب سريع الإيقاع، قوالب توزيع، ومونتاج فيديو عبر المنصات.",
      "catalog.eyebrow": "أعمال مختارة",
      "catalog.title": "المشاريع",
      "catalog.lead": "أربعة مسارات للعمل. انتقل بينها، أو مرّر بالأسفل.",
      "catalog.hint": "مرّر · أو انتقل إلى:",
      "cat.web": "مشاريع ويب",
      "cat.asset": "تصميم الأصول",
      "cat.dev": "خدمات التطوير",
      "cat.content": "المحتوى والإعلام",
      "cat.count": "مشاريع",
      "link.open": "فتح",
      "contact.eyebrow": "تواصل",
      "contact.title": "لنبنِ شيئًا معًا.",
      "contact.sub": "لديك مشروع، أو سيرفر تريد تجهيزه، أو تريد فقط إلقاء التحية؟ بريدي مفتوح دائمًا.",
      "contact.cta": "راسلني",
      "footer.top": "العودة للأعلى",
      "footer.line": "© {year} Teddz — بُني بواسطة مطوّر واحد.",
      "meta.title": "تيدز — مطوّر ويب واستوديو فردي",
      "meta.desc": "بسيطة، سريعة، خصوصيتك أولًا. مطوّر ويب يدير استوديو فرديًا يبني مواقع وأدوات وألعابًا.",
    },
  },
};
