window.SITE = {
  brand: {
    name: "Teddz",
    altNames: "Teddz · Teddzfr · Frteddz",
    role: "Web Developer & One-Person Studio",
    baseUrl: "https://frteddz.github.io",
    siteName: "Teddz - Portfolio",
  },
  links: {
    github: "https://github.com/frteddz",
    x: "https://x.com/teddzfr",
    youtube: "https://www.youtube.com/@frteddz",
    instagram: "https://www.instagram.com/teddzfr/",
    tiktok: "https://www.tiktok.com/@teddz.fr",
    email: "mailto:teddzfr@proton.me",
    emailPlain: "teddzfr@proton.me",
  },
  categories: [
    { id: "web", tone: "dark" },
    { id: "asset", tone: "light" },
    { id: "dev", tone: "dark" },
    { id: "content", tone: "light" },
  ],
  projects: {
    web: [
      
      
      
{
        slug: "juno",
        name: "JUNO",
        url: "https://frteddz.github.io/JUNO/",
        img: { webp: "juno.webp", jpg: "juno.jpg" },
        desc: {
          en: "A local-first terminal assistant. Open apps, set timers, do the math. Optional DeepSeek AI.",
          ar: "مساعد محلي في الطرفية. افتح التطبيقات، وعيّن مؤقتين، واحسب. DeepSeek AI اختياري.",
        },
        tag: { en: "Terminal Assistant", ar: "مساعد طرفية" },
        alt: {
          en: "JUNO - terminal assistant, screenshot",
          ar: "JUNO - مساعد طرفية، لقطة شاشة",
        },
      },
      {
        slug: "cedrus",
        name: "Cedrus CLI",
        url: "https://frteddz.github.io/cedrus/",
        img: { webp: "cedrus.webp", jpg: "cedrus.jpg" },
        desc: {
          en: "A command-line tool that connects to any web-based public AI and turns it into an IDE.",
          ar: "أداة سطر أوامر تتصل بأي ذكاء اصطناعي عام ويحوّله إلى بيئة تطوير متكاملة.",
        },
        tag: { en: "CLI Tool", ar: "أداة سطر أوامر" },
        alt: {
          en: "Cedrus CLI - turn any web AI into a coding agent, screenshot",
          ar: "Cedrus CLI - حوّل أي ذكاء اصطناعي إلى عميل برمجة، لقطة شاشة",
        },
      },
      
      
      
      
      
      
      
      
      
      
      
      
    ],
    asset: [
      {
        slug: "modrinth",
        name: "Modrinth Creator",
        url: "https://modrinth.com/user/teddz",
        img: { webp: "modrinth.webp", jpg: "modrinth.jpg" },
        desc: {
          en: "Developing highly optimized PvP resource packs and UI layouts focused on competitive visibility and frame-rate optimization.",
          ar: "تطوير حزم موارد PvP محسّنة بعناية وتخطيطات واجهات تركّز على الرؤية التنافسية وتحسين معدل الإطارات.",
        },
        tag: { en: "Texturing · Optimization", ar: "تلوين · تحسين" },
        alt: {
          en: "Modrinth creator profile, screenshot",
          ar: "ملف Modrinth، لقطة شاشة",
        },
      },
    ],
    dev: [
      {
        slug: "builtbybit",
        name: "BuiltByBit",
        url: "https://builtbybit.com/members/teddz.672080/",
        img: { webp: "builtbybit.webp", jpg: "builtbybit.jpg" },
        desc: {
          en: "Providing premium configuration services, custom setups, and administrative assets for community server networks.",
          ar: "تقديم خدمات إعدادات متميزة وتجهيزات مخصصة وأصول إدارية لشبكات سيرفرات المجتمعات.",
        },
        tag: { en: "Configurations", ar: "إعدادات" },
        alt: {
          en: "BuiltByBit profile, screenshot",
          ar: "ملف BuiltByBit، لقطة شاشة",
        },
      },
      {
        slug: "fiverr",
        name: "Fiverr",
        url: "https://fiverr.com/teddzfr",
        img: { webp: null, jpg: "fiverr.png" },
        desc: {
          en: "Freelance development shop offering premium configuration services and custom setups.",
          ar: "متجر تطوير مستقل يقدم خدمات إعدادات متميزة وتجهيزات مخصصة.",
        },
        tag: { en: "Freelance", ar: "عمل حر" },
        alt: { en: "Fiverr shop - Teddz", ar: "متجر Fiverr - Teddz" },
      },
      {
        slug: "kofi",
        name: "Ko-fi",
        url: "https://ko-fi.com/majdsafi",
        img: { webp: null, jpg: "ko-fi.png" },
        desc: {
          en: "Support my work by buying me a coffee.",
          ar: "ادعم عملي بدعوتي على فنجان قهوة.",
        },
        tag: { en: "Support", ar: "دعم" },
        alt: { en: "Ko-fi page - Teddz", ar: "صفحة Ko-fi - Teddz" },
      },
    ],
    content: [
      {
        slug: "youtube",
        name: "YouTube",
        url: "https://www.youtube.com/@frteddz",
        img: null,
        desc: {
          en: "Producing fast-paced video content, clip pacing templates, and gaming media.",
          ar: "إنتاج محتوى فيديو سريع الإيقاع، قوالب توزيع للمقاطع، ووسائط ألعاب.",
        },
        tag: { en: "Video Editing", ar: "مونتاج فيديو" },
        alt: { en: "YouTube channel - abstract placeholder", ar: "قناة يوتيوب - صورة تجريدية" },
      },
      {
        slug: "tiktok",
        name: "TikTok",
        url: "https://www.tiktok.com/@teddz.fr",
        img: null,
        desc: {
          en: "Gaming media and short-form content across platforms.",
          ar: "وسائط ألعاب ومحتوى قصير عبر المنصات.",
        },
        tag: { en: "Short-form", ar: "محتوى قصير" },
        alt: { en: "TikTok profile - abstract placeholder", ar: "ملف TikTok - صورة تجريدية" },
      },
    ],
  },
  t: {
    en: {
      "nav.work": "Work",
      "nav.about": "About",
      "nav.services": "Services",
      "nav.contact": "Contact",
      "nav.menu": "Open menu",
      "nav.close": "Close menu",
      "nav.lang.ar": "العربية",
      "nav.lang.en": "English",
      "a11y.skip": "Skip to content",
      "hero.eyebrow": "Web Developer · One-Person Studio",
      "hero.altnames": "Teddz · Teddzfr · Frteddz",
      "hero.tagline.pre": "Simple, fast,",
      "hero.tagline.accent": "privacy-first.",
      "hero.lead": "Web developer and one-person studio building websites, tools, and games that are simple, fast, and respect your privacy.",
      "hero.cta.work": "View work",
      "hero.cta.contact": "Get in touch",
      "hero.scroll": "Scroll to explore",
      "m1": "Web Development",
      "m2": "UI Layouts",
      "m3": "Minecraft Resource Packs",
      "m4": "Privacy First",
      "m5": "Performance",
      "m6": "Video Editing",
      "m8": "Clean Code",
      "about.eyebrow": "About",
      "about.title": "Software that respects the person using it.",
      "about.body1": "This is my personal portfolio - a place to publish the tools and projects I build. Everything here is made by me, Teddz, one developer at a time.",
      "about.body2": "I believe software should be simple, fast, and respect your privacy.",
      "v1.t": "Built by One Dev",
      "v1.d": "Every project is crafted by Teddz - one developer, from idea to launch.",
      "v2.t": "Privacy First",
      "v2.d": "Tools that run in your browser. No tracking, no data leaving your device.",
      "v3.t": "Always Free at Core",
      "v3.d": "The essential features of every tool stay free. No paywalls, no tricks.",
      "v4.t": "Open to Contributors",
      "v4.d": "Want to publish a project here? My inbox is open - let's build together.",
      "services.eyebrow": "What I do",
      "services.title": "Four lanes, one developer.",
      "s1.t": "Web Development",
      "s1.d": "Fast, accessible websites and web apps - simple by design.",
      "s2.t": "Asset & Resource Design",
      "s2.d": "Highly optimized PvP resource packs and UI layouts for competitive visibility and frame-rate.",
      "s3.t": "Dev & Freelance Services",
      "s3.d": "Premium configurations, custom setups, and admin assets for server networks.",
      "s4.t": "Content & Media",
      "s4.d": "Fast-paced gaming content, clip pacing, and video editing across platforms.",
      "catalog.eyebrow": "Selected Work",
      "catalog.title": "Projects",
      "catalog.lead": "Four lanes of work. Jump between them, or scroll through.",
      "catalog.hint": "Scroll · or jump:",
      "cat.web": "Web Projects",
      "cat.asset": "Asset Design",
      "cat.dev": "Dev Services",
      "cat.content": "Content & Media",
      "cat.count": "projects",
      "link.open": "Open",
      "contact.eyebrow": "Contact",
      "contact.title": "Let's build something together.",
      "contact.sub": "Have a project, a server to set up, or just want to say hi? My inbox is open.",
      "contact.cta": "Email me",
      "footer.top": "Back to top",
      "footer.line": "© {year} Teddz - built by one developer.",
      "meta.title": "Teddz - Web Developer & One-Person Studio",
      "meta.desc": "Simple, fast, privacy-first. Web developer and one-person studio building websites, tools, and games.",
    },
    ar: {
      "nav.work": "الأعمال",
      "nav.about": "من أنا",
      "nav.services": "الخدمات",
      "nav.contact": "تواصل",
      "nav.menu": "افتح القائمة",
      "nav.close": "أغلق القائمة",
      "nav.lang.ar": "العربية",
      "nav.lang.en": "English",
      "a11y.skip": "تخطّي إلى المحتوى",
      "hero.eyebrow": "مطوّر ويب · استوديو فردي",
      "hero.altnames": "تيدز · Teddzfr · Frteddz",
      "hero.tagline.pre": "بسيطة، سريعة،",
      "hero.tagline.accent": "خصوصيتك أولًا.",
      "hero.lead": "مطوّر ويب يدير استوديو فرديًا - أبني مواقع وأدوات وألعابًا بسيطة وسريعة وتحترم خصوصيتك.",
      "hero.cta.work": "شاهد أعمالي",
      "hero.cta.contact": "تواصل معي",
      "hero.scroll": "مرّر للاستكشاف",
      "m1": "تطوير الويب",
      "m2": "تصاميم واجهات",
      "m3": "حزم موارد ماينكرافت",
      "m4": "الخصوصية أولًا",
      "m5": "الأداء",
      "m6": "مونتاج الفيديو",
      "m8": "كود نظيف",
      "about.eyebrow": "من أنا",
      "about.title": "برمجيات تحترم من يستخدمها.",
      "about.body1": "هذه هي صفحتي الشخصية - مكان أنشر فيه الأدوات والمشاريع التي أبنيها. كل شيء هنا صنعه أنا، Teddz، مطوّرًا واحدًا في كل مرة.",
      "about.body2": "أؤمن أن البرمجيات يجب أن تكون بسيطة وسريعة وتحترم خصوصيتك.",
      "v1.t": "من صنع مطوّر واحد",
      "v1.d": "كل مشروع يصنعه Teddz - مطوّر واحد، من الفكرة حتى الإطلاق.",
      "v2.t": "الخصوصية أولًا",
      "v2.d": "أدوات تعمل في متصفحك. لا تتبّع، ولا بيانات تغادر جهازك.",
      "v3.t": "مجاني في جوهره",
      "v3.d": "الميزات الأساسية لكل أداة تبقى مجانية دائمًا. لا جدران دفع ولا حيل.",
      "v4.t": "مفتوح للمساهمين",
      "v4.d": "تريد نشر مشروع هنا؟ بريدي مفتوح - لنبنِ معًا.",
      "services.eyebrow": "ماذا أفعل",
      "services.title": "أربعة مسارات، مطوّر واحد.",
      "s1.t": "تطوير الويب",
      "s1.d": "مواقع وتطبيقات ويب سريعة وسهلة الوصول - بسيطة بالتصميم.",
      "s2.t": "تصميم الأصول والموارد",
      "s2.d": "حزم موارد PvP محسّنة بعناية وتخطيطات واجهات للرؤية التنافسية وتحسين معدل الإطارات.",
      "s3.t": "التطوير والعمل الحر",
      "s3.d": "إعدادات متميزة وتجهيزات مخصصة وأصول إدارية لشبكات السيرفرات.",
      "s4.t": "المحتوى والإعلام",
      "s4.d": "محتوى ألعاب سريع الإيقاع، قوالب توزيع، ومونتاج فيديو عبر المنصات.",
      "catalog.eyebrow": "أعمال مختارة",
      "catalog.title": "المشاريع",
      "catalog.lead": "أربعة مسارات للعمل. انتقل بينها، أو مرّر بالأسفل.",
      "catalog.hint": "مرّر · أو انتقل إلى:",
      "cat.web": "مشاريع ويب",
      "cat.asset": "تصميم الأصول",
      "cat.dev": "خدمات التطوير",
      "cat.content": "المحتوى والإعلام",
      "cat.count": "مشاريع",
      "link.open": "فتح",
      "contact.eyebrow": "تواصل",
      "contact.title": "لنبنِ شيئًا معًا.",
      "contact.sub": "لديك مشروع، أو سيرفر تريد تجهيزه، أو تريد فقط إلقاء التحية؟ بريدي مفتوح دائمًا.",
      "contact.cta": "راسلني",
      "footer.top": "العودة للأعلى",
      "footer.line": "© {year} Teddz - بُني بواسطة مطوّر واحد.",
      "meta.title": "تيدز - مطوّر ويب واستوديو فردي",
      "meta.desc": "بسيطة، سريعة، خصوصيتك أولًا. مطوّر ويب يدير استوديو فرديًا يبني مواقع وأدوات وألعابًا.",
    },
  },
};
